---

- name: play for deployment
  hosts: webservers
  become: yes
  become_user: jenkins
  tasks:
    - name: deploying war file
      copy:
        src: target/sampleA.war
        dest: /home/ec2-user/apps/tomcat/webapps/
        owner: ec2-user
        group: ec2-user
